#!/usr/bin/env python3
"""
Write database/schema/schema.sql: the PostgreSQL DDL for every ORM model.

Generated from backend/app/models (not from a live database), so it can run anywhere:

    cd backend && PYTHONPATH=. .venv/bin/python ../database/schema/export_schema.py
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "backend"))

from sqlalchemy.dialects import postgresql  # noqa: E402
from sqlalchemy.schema import CreateIndex, CreateTable  # noqa: E402

from app.db.base import Base  # noqa: E402
import app.models  # noqa: E402,F401

OUTPUT = REPO_ROOT / "database" / "schema" / "schema.sql"


def main() -> int:
    dialect = postgresql.dialect()
    lines = ["-- Generated by database/schema/export_schema.py from backend/app/models. Do not edit by hand.",
             "-- Apply real changes through Alembic (backend/alembic/versions).", ""]
    for table in Base.metadata.sorted_tables:
        lines.append(str(CreateTable(table).compile(dialect=dialect)).strip() + ";")
        for index in sorted(table.indexes, key=lambda i: i.name or ""):
            lines.append(str(CreateIndex(index).compile(dialect=dialect)).strip() + ";")
        lines.append("")
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)} ({len(Base.metadata.sorted_tables)} tables)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
