-- Generated by database/schema/export_schema.py from backend/app/models. Do not edit by hand.
-- Apply real changes through Alembic (backend/alembic/versions).

CREATE TABLE model_versions (
	id UUID NOT NULL, 
	name VARCHAR(160) NOT NULL, 
	version VARCHAR(64) NOT NULL, 
	feature_schema_version VARCHAR(32) NOT NULL, 
	artifact_uri TEXT NOT NULL, 
	metrics_json JSONB DEFAULT '{}' NOT NULL, 
	is_active BOOLEAN DEFAULT 'false' NOT NULL, 
	trained_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_model_versions_name_version UNIQUE (name, version)
);

CREATE TABLE revoked_tokens (
	token_id UUID NOT NULL, 
	expires_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (token_id)
);
CREATE INDEX ix_revoked_tokens_expires_at ON revoked_tokens (expires_at);

CREATE TABLE roles (
	id UUID NOT NULL, 
	name VARCHAR(7) NOT NULL, 
	description TEXT, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (name)
);

CREATE TABLE users (
	id UUID NOT NULL, 
	role_id UUID NOT NULL, 
	email VARCHAR(320) NOT NULL, 
	password_hash VARCHAR(255) NOT NULL, 
	display_name VARCHAR(120) NOT NULL, 
	is_active BOOLEAN DEFAULT 'true' NOT NULL, 
	last_login_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(role_id) REFERENCES roles (id) ON DELETE RESTRICT, 
	UNIQUE (email)
);

CREATE TABLE audit_logs (
	id UUID NOT NULL, 
	actor_user_id UUID, 
	action VARCHAR(120) NOT NULL, 
	resource_type VARCHAR(80) NOT NULL, 
	resource_id UUID, 
	request_id VARCHAR(80), 
	ip_address VARCHAR(45), 
	metadata_json JSONB DEFAULT '{}' NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(actor_user_id) REFERENCES users (id) ON DELETE SET NULL
);
CREATE INDEX ix_audit_logs_created_at ON audit_logs (created_at);

CREATE TABLE traffic_sources (
	id UUID NOT NULL, 
	name VARCHAR(160) NOT NULL, 
	source_type VARCHAR(10) NOT NULL, 
	description TEXT, 
	is_active BOOLEAN DEFAULT 'true' NOT NULL, 
	created_by_user_id UUID, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (name), 
	FOREIGN KEY(created_by_user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE TABLE host_entities (
	id UUID NOT NULL, 
	traffic_source_id UUID NOT NULL, 
	ip_address VARCHAR(45) NOT NULL, 
	hostname VARCHAR(255), 
	entity_type VARCHAR(40) NOT NULL, 
	first_seen_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	last_seen_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_host_entities_source_ip UNIQUE (traffic_source_id, ip_address), 
	FOREIGN KEY(traffic_source_id) REFERENCES traffic_sources (id) ON DELETE CASCADE
);

CREATE TABLE ingestion_jobs (
	id UUID NOT NULL, 
	traffic_source_id UUID NOT NULL, 
	requested_by_user_id UUID, 
	original_filename VARCHAR(255) NOT NULL, 
	content_hash VARCHAR(64) NOT NULL, 
	status VARCHAR(9) NOT NULL, 
	total_rows INTEGER DEFAULT '0' NOT NULL, 
	accepted_rows INTEGER DEFAULT '0' NOT NULL, 
	skipped_rows INTEGER DEFAULT '0' NOT NULL, 
	error_message TEXT, 
	started_at TIMESTAMP WITH TIME ZONE, 
	completed_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(traffic_source_id) REFERENCES traffic_sources (id) ON DELETE RESTRICT, 
	FOREIGN KEY(requested_by_user_id) REFERENCES users (id) ON DELETE SET NULL
);
CREATE INDEX ix_ingestion_jobs_source_status_created ON ingestion_jobs (traffic_source_id, status, created_at);

CREATE TABLE traffic_windows (
	id UUID NOT NULL, 
	traffic_source_id UUID NOT NULL, 
	window_start TIMESTAMP WITH TIME ZONE NOT NULL, 
	window_end TIMESTAMP WITH TIME ZONE NOT NULL, 
	window_seconds INTEGER NOT NULL, 
	scope_type VARCHAR(6) NOT NULL, 
	scope_key VARCHAR(255) NOT NULL, 
	flow_count INTEGER DEFAULT '0' NOT NULL, 
	packet_count BIGINT DEFAULT '0' NOT NULL, 
	byte_count BIGINT DEFAULT '0' NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_traffic_windows_valid_range CHECK (window_end > window_start), 
	CONSTRAINT uq_traffic_windows_source_scope_range UNIQUE (traffic_source_id, scope_type, scope_key, window_start, window_end), 
	FOREIGN KEY(traffic_source_id) REFERENCES traffic_sources (id) ON DELETE RESTRICT
);
CREATE INDEX ix_traffic_windows_source_range ON traffic_windows (traffic_source_id, window_start, window_end);

CREATE TABLE predictions (
	id UUID NOT NULL, 
	observation_window_id UUID NOT NULL, 
	model_version_id UUID, 
	forecast_window_start TIMESTAMP WITH TIME ZONE NOT NULL, 
	forecast_window_end TIMESTAMP WITH TIME ZONE NOT NULL, 
	risk_score NUMERIC(5, 2) NOT NULL, 
	risk_level VARCHAR(8) NOT NULL, 
	predicted_attack_type VARCHAR(80), 
	confidence_score NUMERIC(4, 3) NOT NULL, 
	is_fallback BOOLEAN DEFAULT 'false' NOT NULL, 
	is_uncertain BOOLEAN DEFAULT 'false' NOT NULL, 
	is_ood BOOLEAN DEFAULT 'false' NOT NULL, 
	explanation_json JSONB DEFAULT '[]' NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_predictions_valid_forecast_range CHECK (forecast_window_end > forecast_window_start), 
	CONSTRAINT ck_predictions_risk_score CHECK (risk_score >= 0 AND risk_score <= 100), 
	CONSTRAINT ck_predictions_confidence_score CHECK (confidence_score >= 0 AND confidence_score <= 1), 
	FOREIGN KEY(observation_window_id) REFERENCES traffic_windows (id) ON DELETE RESTRICT, 
	FOREIGN KEY(model_version_id) REFERENCES model_versions (id) ON DELETE SET NULL
);
CREATE INDEX ix_predictions_created_risk_level ON predictions (created_at, risk_level);
CREATE INDEX ix_predictions_forecast_range ON predictions (forecast_window_start, forecast_window_end);

CREATE TABLE raw_flows (
	id UUID NOT NULL, 
	traffic_source_id UUID NOT NULL, 
	ingestion_job_id UUID NOT NULL, 
	observed_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	src_ip VARCHAR(45) NOT NULL, 
	dst_ip VARCHAR(45) NOT NULL, 
	src_port INTEGER, 
	dst_port INTEGER, 
	protocol VARCHAR(16) NOT NULL, 
	packet_count INTEGER NOT NULL, 
	byte_count BIGINT NOT NULL, 
	duration_ms INTEGER, 
	tcp_flags VARCHAR(32), 
	failed_connection BOOLEAN, 
	extra_json JSONB DEFAULT '{}' NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(traffic_source_id) REFERENCES traffic_sources (id) ON DELETE RESTRICT, 
	FOREIGN KEY(ingestion_job_id) REFERENCES ingestion_jobs (id) ON DELETE CASCADE
);
CREATE INDEX ix_raw_flows_observed_at ON raw_flows (observed_at);
CREATE INDEX ix_raw_flows_src_dst_ip ON raw_flows (src_ip, dst_ip);

CREATE TABLE window_features (
	id UUID NOT NULL, 
	traffic_window_id UUID NOT NULL, 
	feature_schema_version VARCHAR(32) NOT NULL, 
	features_json JSONB NOT NULL, 
	is_complete BOOLEAN DEFAULT 'true' NOT NULL, 
	missing_fields_json JSONB DEFAULT '[]' NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (traffic_window_id), 
	FOREIGN KEY(traffic_window_id) REFERENCES traffic_windows (id) ON DELETE CASCADE
);

CREATE TABLE alerts (
	id UUID NOT NULL, 
	prediction_id UUID NOT NULL, 
	target_host_id UUID, 
	title VARCHAR(255) NOT NULL, 
	summary TEXT NOT NULL, 
	severity VARCHAR(8) NOT NULL, 
	status VARCHAR(13) NOT NULL, 
	recommended_actions_json JSONB DEFAULT '[]' NOT NULL, 
	resolved_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (prediction_id), 
	FOREIGN KEY(prediction_id) REFERENCES predictions (id) ON DELETE CASCADE, 
	FOREIGN KEY(target_host_id) REFERENCES host_entities (id) ON DELETE SET NULL
);
CREATE INDEX ix_alerts_status_severity_created ON alerts (status, severity, created_at);

CREATE TABLE alert_events (
	id UUID NOT NULL, 
	alert_id UUID NOT NULL, 
	actor_user_id UUID, 
	event_type VARCHAR(80) NOT NULL, 
	from_status VARCHAR(13), 
	to_status VARCHAR(13), 
	note TEXT, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(alert_id) REFERENCES alerts (id) ON DELETE CASCADE, 
	FOREIGN KEY(actor_user_id) REFERENCES users (id) ON DELETE SET NULL
);
